project:
  type: book
  output-dir: _book
  resources:
    - code/**

book:
  title: "Containerization for Beginners"
  author: "Mateo Langston Smith"
  reader-mode: false
  cover-image: images/docker-mark-blue.png
  sidebar:
    logo: images/logo_stack.svg
    pinned: true
  page-footer:
    right: <a href="http://creativecommons.org/licenses/by-sa/4.0/"><img src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>
  site-url: https://southernmethodistuniversity.github.io/containerization-for-beginners/
  repo-url: https://github.com/SouthernMethodistUniversity/containerization-for-beginners
  repo-branch: main
  repo-actions: [edit, issue]
  chapters: # TODO update entire structure to represent your structure
    - index.qmd
    - part: section1.qmd
      chapters: 
        - chapter1.qmd
        - chapter2.qmd
    - part: section2.qmd
      chapters: 
        - chapter3.qmd
        - chapter4.qmd
    - next_steps.qmd

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Mateo Langston Smith"
    callout-appearance: simple

editor: source